List<String> courseList = [
  "Accounting",
  "Aerospace Engineering",
  "Architecture",
  "Biomedical Science",
  "Business Administration",
  "Chemical Engineering",
  "Computer Science",
  "Dentistry",
  "Economics",
  "Education Studies",
  "Electronic Engineering",
  "English Literature",
  "Fashion Design",
  "Finance",
  "Graphic Design",
  "History",
  "International Relations",
  "Journalism",
  "Law",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Physics",
  "Politics",
  "Psychology",
  "Sociology",
  "Software Engineering",
  "Sports Science"
];
